from typing import Union
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score
import pandas as pd
import numpy as np
from joblib import Parallel, delayed


class ClusteringSelector:
    """
    ClusteringSelector is a class for selecting the best clustering algorithm
    and parameters for a given dataset.

    It evaluates and compares the performance of various clustering algorithms
    such as K-Means, Agglomerative Clustering, and DBSCAN.

    The selection is based on the silhouette score, and the class stores the
    best-performing algorithm, its parameters, and the resulting cluster
    labels.

    Attributes:
        data (pd.DataFrame): The dataset on which clustering algorithms will
                             be applied.
        best_algorithm (str): Name of the best-performing clustering algorithm.
        best_params (list): Parameters of the best-performing clustering
                            algorithm.
        best_labels (np.array): Cluster labels generated by the
                                best-performing algorithm.
        cluster (int, optional): Number of clusters to be used, if specified.
        kmeans_labels (np.array): Labels generated by the K-Means algorithm.
        agglomerative_labels (np.array): Labels generated by the Agglomerative
                                         Clustering algorithm.
        dbscan_labels (np.array): Labels generated by the DBSCAN algorithm.
        best_score_total (float): Highest silhouette score achieved among all
                                  algorithms.
        linkage_values (list): Different linkage methods to be tested with
                               Agglomerative Clustering.
        eps_values (list): Different 'eps' values to be tested with DBSCAN.
        min_samples_values (list): Different 'min_samples' values to be tested
                                   with DBSCAN.
        n_clusters_values (list): Different numbers of clusters to be tested.
    """
    def __init__(self, data: pd.DataFrame, cluster:  Union[int, None] = None, n_jobs: int = -1):
        self.data = data
        self.best_algorithm = None
        self.best_params = [0]*5
        self.best_labels = None
        self.cluster = cluster
        self.n_jobs = n_jobs  # -1 means use all available cores
        self.kmeans_labels = None
        self.agglomerative_labels = None
        self.dbscan_labels = None
        self.best_score_total = float('-inf')
        self.linkage_values = ['ward', 'complete', 'average']
        self.eps_values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
        self.min_samples_values = [2, 3, 4, 5, 6]
        self.n_clusters_values = ([2, 3, 4] if self.cluster is None
                                  else [self.cluster])

    def select_best_clustering(self):
        """
        Evaluates and selects the best clustering algorithm for the dataset.
        This method tests K-Means, Agglomerative Clustering, and DBSCAN with
        various parameters, comparing their performance using the silhouette
        score.
        The method updates the class attributes with the best-performing
        algorithm's name, parameters, and labels.
        """
        # Helper function for K-Means evaluation
        def eval_kmeans(n_clusters):
            kmeans = KMeans(n_clusters=n_clusters, random_state=42)
            labels = kmeans.fit_predict(self.data)
            score = silhouette_score(self.data, labels) if len(set(labels)) > 2 else 0
            return n_clusters, labels, score

        # Helper function for Agglomerative Clustering evaluation
        def eval_agglomerative(n_clusters, linkage):
            aggclust = AgglomerativeClustering(n_clusters=n_clusters, linkage=linkage)
            labels = aggclust.fit_predict(self.data)
            score = silhouette_score(self.data, labels) if len(set(labels)) > 2 else 0
            return n_clusters, linkage, labels, score

        # Helper function for DBSCAN evaluation
        def eval_dbscan(eps, min_samples):
            dbscan = DBSCAN(eps=eps, min_samples=min_samples)
            labels = dbscan.fit_predict(self.data)
            score = silhouette_score(self.data, labels) if len(set(labels)) > 2 else 0
            return eps, min_samples, labels, score

        # Test Parameters
        best_score_dbscan = float('-inf')
        best_score_kmeans = float('-inf')
        best_score_aggclust = float('-inf')

        # Parallel K-Means evaluation
        kmeans_results = Parallel(n_jobs=self.n_jobs)(
            delayed(eval_kmeans)(n_clusters) for n_clusters in self.n_clusters_values
        )

        for n_clusters, labels, score in kmeans_results:
            if score > best_score_kmeans:
                self.best_params[0] = n_clusters
                best_score_kmeans = score
                self.kmeans_labels = labels

        # Parallel Agglomerative Clustering evaluation
        aggclust_params = [(n_clusters, linkage)
                           for n_clusters in self.n_clusters_values
                           for linkage in self.linkage_values]
        aggclust_results = Parallel(n_jobs=self.n_jobs)(
            delayed(eval_agglomerative)(n_clusters, linkage)
            for n_clusters, linkage in aggclust_params
        )

        for n_clusters, linkage, labels, score in aggclust_results:
            if score > best_score_aggclust:
                best_score_aggclust = score
                self.best_params[1] = n_clusters
                self.best_params[2] = linkage
                self.agglomerative_labels = labels

        # Parallel DBSCAN evaluation
        dbscan_params = [(eps, min_samples)
                         for eps in self.eps_values
                         for min_samples in self.min_samples_values]
        dbscan_results = Parallel(n_jobs=self.n_jobs)(
            delayed(eval_dbscan)(eps, min_samples)
            for eps, min_samples in dbscan_params
        )

        for eps, min_samples, labels, score in dbscan_results:
            if score > best_score_dbscan:
                self.best_params[3] = eps
                self.best_params[4] = min_samples
                best_score_dbscan = score
                self.dbscan_labels = labels

        # Select best overall algorithm
        kmeans_score = best_score_kmeans
        aggclust_score = best_score_aggclust
        dbscan_score = best_score_dbscan

        if kmeans_score > self.best_score_total:
            self.best_score_total = kmeans_score
            self.best_algorithm = "K-Means"
            self.best_labels = self.kmeans_labels

        if aggclust_score > self.best_score_total:
            self.best_score_total = aggclust_score
            self.best_algorithm = "Agglomerative Clustering"
            self.best_labels = self.agglomerative_labels

        if dbscan_score > self.best_score_total and self.cluster is None:
            self.best_score_total = dbscan_score
            self.best_algorithm = "DBSCAN"
            self.best_labels = self.dbscan_labels

        if self.best_algorithm == "DBSCAN":
            clusters = max(self.best_labels) + 1
            # Since the classifier does not work with negative classes,
            # it is necessary to adjust the labels that do not belong to any
            # cluster and are labeled as the last cluster.
            self.best_labels[self.best_labels == -1] = clusters

    def normalize_labels(self, x, y):
        """
        Normalizes or standardizes clustering labels.
        This method might be used to adjust labels to a common scale or format.

        Parameters:
            labels (np.array): Array of cluster labels to be normalized.

        Returns:
            np.array: Normalized or standardized labels.
        """
        labels1 = x
        labels2 = y
        # Create an array to save the updated values of the second array
        updated_labels2 = np.copy(labels2)

        # Create a dicctionary to save the correspondances of the labels
        correspondence_dict = {}

        for label1, label2 in zip(labels1, labels2):
            if label1 != label2:
                if label1 not in correspondence_dict:
                    correspondence_dict[label1] = label2

        # Update the values of the second array
        for old_label, new_label in correspondence_dict.items():
            updated_labels2[labels2 == new_label] = old_label

        return updated_labels2

    def get_cluster_labels_df(self):
        """
        Creates a DataFrame containing the cluster labels from each tested
        clustering algorithm.
        The labels are normalized based on the best-performing algorithm.

        Returns:
            pd.DataFrame: A DataFrame with columns for each clustering
                          algorithm's labels.
        """
        labels_df = pd.DataFrame(
            {"K-Means Labels": (self.best_labels
                                if self.best_algorithm == "K-Means"
                                else self.normalize_labels(self.best_labels,
                                                           self.kmeans_labels)
                                ),
             "Agglomerative Labels": (self.best_labels
                                      if self.best_algorithm ==
                                      "Agglomerative Clustering"
                                      else
                                      self.normalize_labels(
                                        self.best_labels,
                                        self.agglomerative_labels)),
             "DBSCAN Labels": (self.best_labels
                               if self.best_algorithm == "DBSCAN"
                               else self.normalize_labels(self.best_labels,
                                                          self.dbscan_labels))
             })
        return labels_df

    def get_best_labels(self):
        """
        Returns the best cluster labels determined by the best-performing
        algorithm.

        Returns:
            np.array: The best cluster labels.
        """
        return self.best_labels

    def get_best_params(self):
        """
        Returns the parameters of the best-performing clustering algorithm.

        Returns:
            list: Parameters of the best-performing algorithm.
        """
        return self.best_params

    def get_best_name(self):
        """
        Returns the name of the best-performing clustering algorithm.

        Returns:
            str: Name of the best-performing algorithm.
        """
        return self.best_algorithm

    def get_most_voted(self):
        """
        Determines the most common label for each data point across different
        clustering algorithms.

        In cases of NaN values, replaces them with labels from the
        best-performing algorithm.

        Returns:
            np.array: Array of the most common labels for each data point.
        """
        labels_df = self.get_cluster_labels_df()
        row_modes = labels_df.mode(axis=1)
        not_nan_index = row_modes.index[~row_modes.isna().any(axis=1)]
        for x in not_nan_index:
            row_modes.loc[x, 0] = self.get_best_labels()[x]

        return np.array(row_modes[0])
